Update README.md
when following the instructions on a fresh linux install, an obscure message is displayed to the effect of;
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for MarkupSafe

Wheel needs to be installed prior to installing the requirements.